DROP TABLE IF EXISTS test_table;
create table
  public.test_table (
    bigintx bigint generated by default as identity,
    bigserialx bigserial,
    bitx bit(1) null,
    bitvaryingx bit varying null,
    booleanx boolean null,
    boxx box null,
    byteax bytea null,
    characterx character(1) null,
    charactervaryingx character varying null,
    cidrx cidr null,
    circlex circle null,
    datex date null,
    doublex double precision null,
    inetx inet null,
    integerx integer null,
    intervalx interval null,
    jsonx json null,
    jsonbx jsonb null,
    linex line null,
    lsegx lseg null,
    macaddrx macaddr null,
    macaddr8x macaddr8 null,
    moneyx money null,
    numericx numeric null,
    pathx path null,
    pg_lsnx pg_lsn null,
    pg_snapshotx pg_snapshot null,
    pointx point null,
    polygonx polygon null,
    realx real null,
    smallintx smallint null,
    smallserialx smallserial,
    serialx serial,
    textx text null,
    timex time without time zone null,
    timewithouttimezone time without time zone null,
    timestampx timestamp without time zone null,
    timestampwithouttimezone timestamp without time zone null,
    tsqueryx tsquery null,
    tsvectorx tsvector null,
    txid_snapshotx txid_snapshot null,
    uuidx uuid null,
    xmlx xml null,
    cleanup int default 1,
    constraint test_table_pkey primary key (bigintx)
  ) tablespace pg_default;
-- We need to add this for serial types otherwise the serial columns will not be recognized as nullable
-- and the insert method will always ask for a value
COMMENT ON COLUMN test_table.bigserialx IS 'serial';
COMMENT ON COLUMN test_table.smallserialx IS 'serial';
COMMENT ON COLUMN test_table.serialx IS 'serial';


-- INSERT INTO test_table (
--     bigintx,
--     bitvaryingx,
--     booleanx,
--     byteax,
--     charactervaryingx,
--     cidrx,
--     circlex,
--     datex,
--     inetx,
--     intervalx,
--     jsonx,
--     linex,
--     macaddrx,
--     macaddr8x,
--     numericx,
--     pathx,
--     pg_snapshotx,
--     pointx,
--     polygonx,
--     smallintx,
--     textx,
--     timex,
--     timestampx,
--     tsqueryx,
--     txid_snapshotx,
--     xmlx
-- ) VALUES (
--     1,                             -- bigintx (Primary Key)
--     B'101',                        -- bitvaryingx
--     TRUE,                          -- booleanx
--     E'\\xDEADBEEF',                -- byteax
--     'example',                     -- charactervaryingx
--     '192.168.100.128/25',          -- cidrx
--     '<(0,0),1>',                   -- circlex
--     '2024-06-21',                  -- datex
--     '192.168.0.1',                 -- inetx
--     '1 year 2 months 3 days',      -- intervalx
--     '{"key": "value"}',            -- jsonx
--     '{0,1,2}',                     -- linex
--     '08:00:2b:01:02:03',           -- macaddrx
--     '08-00-2b-01-02-03-04-05',     -- macaddr8x
--     123.45,                        -- numericx
--     '((1,1),(2,2))',               -- pathx
--     '10:20:10,14,15',              -- pg_snapshotx
--     '(1,1)',                       -- pointx
--     '((1,1),(1,0),(0,0))',         -- polygonx
--     32767,                         -- smallintx
--     'some text',                   -- textx
--     '13:45:00',                    -- timex
--     '2024-06-21 13:45:00',         -- timestampx
--     'fat & rat',                   -- tsqueryx
--     '1:1:',                        -- txid_snapshotx
--     '<example>XML content</example>' -- xmlx
-- );
