version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/cli"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/web"
    schedule:
      interval: weekly
