// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class BinaryXmlTypes implements SupadartClass<BinaryXmlTypes> {
  final String id;
  final String? colBytea;
  final List<String>? colByteaArray;
  final String? colXml;
  final List<String>? colXmlArray;

  const BinaryXmlTypes({
    required this.id,
    this.colBytea,
    this.colByteaArray,
    this.colXml,
    this.colXmlArray,
  });

  static String get table_name => 'binary_xml_types';
  static String get c_id => 'id';
  static String get c_colBytea => 'col_bytea';
  static String get c_colByteaArray => 'col_bytea_array';
  static String get c_colXml => 'col_xml';
  static String get c_colXmlArray => 'col_xml_array';

  static List<BinaryXmlTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(BinaryXmlTypes.fromJson).toList();
  }

  static BinaryXmlTypes converterSingle(Map<String, dynamic> data) {
    return BinaryXmlTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? colBytea,
    List<String>? colByteaArray,
    String? colXml,
    List<String>? colXmlArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBytea != null) 'col_bytea': colBytea.toString(),
      if (colByteaArray != null)
        'col_bytea_array': colByteaArray.map((e) => e.toString()).toList(),
      if (colXml != null) 'col_xml': colXml.toString(),
      if (colXmlArray != null)
        'col_xml_array': colXmlArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? colBytea,
    List<String>? colByteaArray,
    String? colXml,
    List<String>? colXmlArray,
  }) {
    return _generateMap(
      id: id,
      colBytea: colBytea,
      colByteaArray: colByteaArray,
      colXml: colXml,
      colXmlArray: colXmlArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? colBytea,
    List<String>? colByteaArray,
    String? colXml,
    List<String>? colXmlArray,
  }) {
    return _generateMap(
      id: id,
      colBytea: colBytea,
      colByteaArray: colByteaArray,
      colXml: colXml,
      colXmlArray: colXmlArray,
    );
  }

  factory BinaryXmlTypes.fromJson(Map<String, dynamic> jsonn) {
    return BinaryXmlTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colBytea:
          jsonn['col_bytea'] != null ? jsonn['col_bytea'].toString() : null,
      colByteaArray: jsonn['col_bytea_array'] != null
          ? (jsonn['col_bytea_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colXml: jsonn['col_xml'] != null ? jsonn['col_xml'].toString() : null,
      colXmlArray: jsonn['col_xml_array'] != null
          ? (jsonn['col_xml_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    String? colBytea,
    List<String>? colByteaArray,
    String? colXml,
    List<String>? colXmlArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBytea != null) 'col_bytea': colBytea,
      if (colByteaArray != null) 'col_bytea_array': colByteaArray,
      if (colXml != null) 'col_xml': colXml,
      if (colXmlArray != null) 'col_xml_array': colXmlArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colBytea: colBytea,
      colByteaArray: colByteaArray,
      colXml: colXml,
      colXmlArray: colXmlArray,
    );
  }

  static const _unset = Object();
  BinaryXmlTypes copyWith({
    Object? id = _unset,
    Object? colBytea = _unset,
    Object? colByteaArray = _unset,
    Object? colXml = _unset,
    Object? colXmlArray = _unset,
  }) {
    return BinaryXmlTypes(
      id: id == _unset ? this.id : id as String,
      colBytea: colBytea == _unset ? this.colBytea : colBytea as String?,
      colByteaArray: colByteaArray == _unset
          ? this.colByteaArray
          : colByteaArray as List<String>?,
      colXml: colXml == _unset ? this.colXml : colXml as String?,
      colXmlArray: colXmlArray == _unset
          ? this.colXmlArray
          : colXmlArray as List<String>?,
    );
  }
}
