// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class CombinedTypesView implements SupadartClass<CombinedTypesView> {
  final String? numericId;
  final int? colInteger;
  final double? colDouble;
  final String? stringId;
  final String? colText;
  final String? colUuid;

  const CombinedTypesView({
    this.numericId,
    this.colInteger,
    this.colDouble,
    this.stringId,
    this.colText,
    this.colUuid,
  });

  static String get table_name => 'combined_types_view';
  static String get c_numericId => 'numeric_id';
  static String get c_colInteger => 'col_integer';
  static String get c_colDouble => 'col_double';
  static String get c_stringId => 'string_id';
  static String get c_colText => 'col_text';
  static String get c_colUuid => 'col_uuid';

  static List<CombinedTypesView> converter(List<Map<String, dynamic>> data) {
    return data.map(CombinedTypesView.fromJson).toList();
  }

  static CombinedTypesView converterSingle(Map<String, dynamic> data) {
    return CombinedTypesView.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? numericId,
    int? colInteger,
    double? colDouble,
    String? stringId,
    String? colText,
    String? colUuid,
  }) {
    return {
      if (numericId != null) 'numeric_id': numericId,
      if (colInteger != null) 'col_integer': colInteger,
      if (colDouble != null) 'col_double': colDouble.toString(),
      if (stringId != null) 'string_id': stringId,
      if (colText != null) 'col_text': colText,
      if (colUuid != null) 'col_uuid': colUuid,
    };
  }

  static Map<String, dynamic> insert({
    String? numericId,
    int? colInteger,
    double? colDouble,
    String? stringId,
    String? colText,
    String? colUuid,
  }) {
    return _generateMap(
      numericId: numericId,
      colInteger: colInteger,
      colDouble: colDouble,
      stringId: stringId,
      colText: colText,
      colUuid: colUuid,
    );
  }

  static Map<String, dynamic> update({
    String? numericId,
    int? colInteger,
    double? colDouble,
    String? stringId,
    String? colText,
    String? colUuid,
  }) {
    return _generateMap(
      numericId: numericId,
      colInteger: colInteger,
      colDouble: colDouble,
      stringId: stringId,
      colText: colText,
      colUuid: colUuid,
    );
  }

  factory CombinedTypesView.fromJson(Map<String, dynamic> jsonn) {
    return CombinedTypesView(
      numericId:
          jsonn['numeric_id'] != null ? jsonn['numeric_id'].toString() : null,
      colInteger: jsonn['col_integer'] != null
          ? int.parse(jsonn['col_integer'].toString())
          : null,
      colDouble: jsonn['col_double'] != null
          ? double.parse(jsonn['col_double'].toString())
          : null,
      stringId:
          jsonn['string_id'] != null ? jsonn['string_id'].toString() : null,
      colText: jsonn['col_text'] != null ? jsonn['col_text'].toString() : null,
      colUuid: jsonn['col_uuid'] != null ? jsonn['col_uuid'].toString() : null,
    );
  }

  static Object New({
    String? numericId,
    int? colInteger,
    double? colDouble,
    String? stringId,
    String? colText,
    String? colUuid,
  }) {
    return {
      if (numericId != null) 'numeric_id': numericId,
      if (colInteger != null) 'col_integer': colInteger,
      if (colDouble != null) 'col_double': colDouble,
      if (stringId != null) 'string_id': stringId,
      if (colText != null) 'col_text': colText,
      if (colUuid != null) 'col_uuid': colUuid,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      numericId: numericId,
      colInteger: colInteger,
      colDouble: colDouble,
      stringId: stringId,
      colText: colText,
      colUuid: colUuid,
    );
  }

  static const _unset = Object();
  CombinedTypesView copyWith({
    Object? numericId = _unset,
    Object? colInteger = _unset,
    Object? colDouble = _unset,
    Object? stringId = _unset,
    Object? colText = _unset,
    Object? colUuid = _unset,
  }) {
    return CombinedTypesView(
      numericId: numericId == _unset ? this.numericId : numericId as String?,
      colInteger: colInteger == _unset ? this.colInteger : colInteger as int?,
      colDouble: colDouble == _unset ? this.colDouble : colDouble as double?,
      stringId: stringId == _unset ? this.stringId : stringId as String?,
      colText: colText == _unset ? this.colText : colText as String?,
      colUuid: colUuid == _unset ? this.colUuid : colUuid as String?,
    );
  }
}
