// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Profiles implements SupadartClass<Profiles> {
  final String id;
  final String? firstName;
  final String? lastName;
  final List<USERGROUP> userGroups;

  const Profiles({
    required this.id,
    this.firstName,
    this.lastName,
    required this.userGroups,
  });

  static String get table_name => 'profiles';
  static String get c_id => 'id';
  static String get c_firstName => 'first_name';
  static String get c_lastName => 'last_name';
  static String get c_userGroups => 'user_groups';

  static List<Profiles> converter(List<Map<String, dynamic>> data) {
    return data.map(Profiles.fromJson).toList();
  }

  static Profiles converterSingle(Map<String, dynamic> data) {
    return Profiles.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? firstName,
    String? lastName,
    List<USERGROUP>? userGroups,
  }) {
    return {
      if (id != null) 'id': id,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (userGroups != null)
        'user_groups':
            userGroups.map((e) => e.toString().split('.').last).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? firstName,
    String? lastName,
    required List<USERGROUP> userGroups,
  }) {
    return _generateMap(
      id: id,
      firstName: firstName,
      lastName: lastName,
      userGroups: userGroups,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? firstName,
    String? lastName,
    List<USERGROUP>? userGroups,
  }) {
    return _generateMap(
      id: id,
      firstName: firstName,
      lastName: lastName,
      userGroups: userGroups,
    );
  }

  factory Profiles.fromJson(Map<String, dynamic> jsonn) {
    return Profiles(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      firstName:
          jsonn['first_name'] != null ? jsonn['first_name'].toString() : null,
      lastName:
          jsonn['last_name'] != null ? jsonn['last_name'].toString() : null,
      userGroups: jsonn['user_groups'] != null
          ? List<USERGROUP>.from(jsonn['user_groups']
              .map((e) => USERGROUP.values.byName(e.toString()))
              .toList())
          : [],
    );
  }

  static Object New({
    String? id,
    String? firstName,
    String? lastName,
    List<USERGROUP>? userGroups,
  }) {
    return {
      if (id != null) 'id': id,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (userGroups != null) 'user_groups': userGroups,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      firstName: firstName,
      lastName: lastName,
      userGroups: userGroups,
    );
  }

  static const _unset = Object();
  Profiles copyWith({
    Object? id = _unset,
    Object? firstName = _unset,
    Object? lastName = _unset,
    Object? userGroups = _unset,
  }) {
    return Profiles(
      id: id == _unset ? this.id : id as String,
      firstName: firstName == _unset ? this.firstName : firstName as String?,
      lastName: lastName == _unset ? this.lastName : lastName as String?,
      userGroups: userGroups == _unset
          ? this.userGroups
          : userGroups as List<USERGROUP>,
    );
  }
}
