// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison,prefer_null_aware_operators

// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

// SDK
import 'package:supabase_flutter/supabase_flutter.dart';

// No geobase needed
// INTL is an official package from Dart and is used for parsing dates
// flutter pub add intl or dart pub add intl
export 'package:intl/intl.dart';

export 'dart:convert';

// No JSONB Model imports needed
// Supadart Class
abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }

  static converter(List<Map<String, dynamic>> data) {
    throw UnimplementedError();
  }

  static converterSingle(Map<String, dynamic> data) {
    throw UnimplementedError();
  }
}

// Supabase Client Extension
extension SupadartClient on SupabaseClient {
  SupabaseQueryBuilder get combined_types_view => from('combined_types_view');
  SupabaseQueryBuilder get embeddings => from('embeddings');
  SupabaseQueryBuilder get enum_types => from('enum_types');
  SupabaseQueryBuilder get misc_types => from('misc_types');
  SupabaseQueryBuilder get string_types => from('string_types');
  SupabaseQueryBuilder get network_types => from('network_types');
  SupabaseQueryBuilder get geometric_types => from('geometric_types');
  SupabaseQueryBuilder get profiles => from('profiles');
  SupabaseQueryBuilder get boolean_bit_types => from('boolean_bit_types');
  SupabaseQueryBuilder get json_types => from('json_types');
  SupabaseQueryBuilder get binary_xml_types => from('binary_xml_types');
  SupabaseQueryBuilder get numeric_types => from('numeric_types');
  SupabaseQueryBuilder get datetime_types => from('datetime_types');
}

// Supabase Storage Client Extension
extension SupadartStorageClient on SupabaseStorageClient {
  StorageFileApi get avatars => from('avatars');
  StorageFileApi get documents => from('documents');
}

// Enums
enum MOOD { happy, sad, neutral, excited, angry }

enum USERGROUP { USERS, ADMIN, MODERATOR }

// Utils
extension DurationFromString on Duration {
  /// Parses an interval in Postgres' default IntervalStyle, such as
  /// "04:05:06.5", "3 days" or "1 year 2 mons -3 days +04:05:06".
  ///
  /// Months and years have no fixed length. As in Postgres' extract(epoch),
  /// a month counts as 30 days and a year as 365.25 days.
  static Duration fromString(String str) {
    final part = RegExp(r'([+-]?\d+) (year|mon|day)s?'
        r'|([+-]?)(\d+):(\d+):(\d+)(?:\.(\d+))?');
    if (str.replaceAll(part, '').trim().isNotEmpty) {
      throw FormatException('Unsupported interval format', str);
    }

    const day = Duration.microsecondsPerDay;
    var micros = 0;
    for (final m in part.allMatches(str)) {
      if (m[1] != null) {
        final n = int.parse(m[1]!);
        micros += switch (m[2]) {
          'year' => n * day * 1461 ~/ 4,
          'mon' => n * day * 30,
          _ => n * day,
        };
      } else {
        final fraction = (m[7] ?? '').padRight(6, '0').substring(0, 6);
        final time = int.parse(m[4]!) * Duration.microsecondsPerHour +
            int.parse(m[5]!) * Duration.microsecondsPerMinute +
            int.parse(m[6]!) * Duration.microsecondsPerSecond +
            int.parse(fraction);
        micros += m[3] == '-' ? -time : time;
      }
    }
    return Duration(microseconds: micros);
  }
}
