// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class BooleanBitTypes implements SupadartClass<BooleanBitTypes> {
  final String id;
  final bool? colBoolean;
  final List<bool>? colBooleanArray;
  final String? colBit;
  final List<String>? colBitArray;
  final String? colBitvarying;
  final List<String>? colBitvaryingArray;

  const BooleanBitTypes({
    required this.id,
    this.colBoolean,
    this.colBooleanArray,
    this.colBit,
    this.colBitArray,
    this.colBitvarying,
    this.colBitvaryingArray,
  });

  static String get schema_name => 'public';
  static String get table_name => 'boolean_bit_types';
  static String get c_id => 'id';
  static String get c_colBoolean => 'col_boolean';
  static String get c_colBooleanArray => 'col_boolean_array';
  static String get c_colBit => 'col_bit';
  static String get c_colBitArray => 'col_bit_array';
  static String get c_colBitvarying => 'col_bitvarying';
  static String get c_colBitvaryingArray => 'col_bitvarying_array';

  static List<BooleanBitTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(BooleanBitTypes.fromJson).toList();
  }

  static BooleanBitTypes converterSingle(Map<String, dynamic> data) {
    return BooleanBitTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    bool? colBoolean,
    List<bool>? colBooleanArray,
    String? colBit,
    List<String>? colBitArray,
    String? colBitvarying,
    List<String>? colBitvaryingArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBoolean != null) 'col_boolean': colBoolean,
      if (colBooleanArray != null)
        'col_boolean_array': colBooleanArray.map((e) => e).toList(),
      if (colBit != null) 'col_bit': colBit.toString(),
      if (colBitArray != null)
        'col_bit_array': colBitArray.map((e) => e.toString()).toList(),
      if (colBitvarying != null) 'col_bitvarying': colBitvarying.toString(),
      if (colBitvaryingArray != null)
        'col_bitvarying_array':
            colBitvaryingArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    bool? colBoolean,
    List<bool>? colBooleanArray,
    String? colBit,
    List<String>? colBitArray,
    String? colBitvarying,
    List<String>? colBitvaryingArray,
  }) {
    return _generateMap(
      id: id,
      colBoolean: colBoolean,
      colBooleanArray: colBooleanArray,
      colBit: colBit,
      colBitArray: colBitArray,
      colBitvarying: colBitvarying,
      colBitvaryingArray: colBitvaryingArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    bool? colBoolean,
    List<bool>? colBooleanArray,
    String? colBit,
    List<String>? colBitArray,
    String? colBitvarying,
    List<String>? colBitvaryingArray,
  }) {
    return _generateMap(
      id: id,
      colBoolean: colBoolean,
      colBooleanArray: colBooleanArray,
      colBit: colBit,
      colBitArray: colBitArray,
      colBitvarying: colBitvarying,
      colBitvaryingArray: colBitvaryingArray,
    );
  }

  factory BooleanBitTypes.fromJson(Map<String, dynamic> jsonn) {
    return BooleanBitTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colBoolean:
          jsonn['col_boolean'] != null ? jsonn['col_boolean'] as bool : null,
      colBooleanArray: jsonn['col_boolean_array'] != null
          ? (jsonn['col_boolean_array'] as List<dynamic>)
              .map((v) => v as bool)
              .toList()
          : null,
      colBit: jsonn['col_bit'] != null ? jsonn['col_bit'].toString() : null,
      colBitArray: jsonn['col_bit_array'] != null
          ? (jsonn['col_bit_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colBitvarying: jsonn['col_bitvarying'] != null
          ? jsonn['col_bitvarying'].toString()
          : null,
      colBitvaryingArray: jsonn['col_bitvarying_array'] != null
          ? (jsonn['col_bitvarying_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    bool? colBoolean,
    List<bool>? colBooleanArray,
    String? colBit,
    List<String>? colBitArray,
    String? colBitvarying,
    List<String>? colBitvaryingArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBoolean != null) 'col_boolean': colBoolean,
      if (colBooleanArray != null) 'col_boolean_array': colBooleanArray,
      if (colBit != null) 'col_bit': colBit,
      if (colBitArray != null) 'col_bit_array': colBitArray,
      if (colBitvarying != null) 'col_bitvarying': colBitvarying,
      if (colBitvaryingArray != null)
        'col_bitvarying_array': colBitvaryingArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colBoolean: colBoolean,
      colBooleanArray: colBooleanArray,
      colBit: colBit,
      colBitArray: colBitArray,
      colBitvarying: colBitvarying,
      colBitvaryingArray: colBitvaryingArray,
    );
  }

  static const _unset = Object();
  BooleanBitTypes copyWith({
    Object? id = _unset,
    Object? colBoolean = _unset,
    Object? colBooleanArray = _unset,
    Object? colBit = _unset,
    Object? colBitArray = _unset,
    Object? colBitvarying = _unset,
    Object? colBitvaryingArray = _unset,
  }) {
    return BooleanBitTypes(
      id: id == _unset ? this.id : id as String,
      colBoolean: colBoolean == _unset ? this.colBoolean : colBoolean as bool?,
      colBooleanArray: colBooleanArray == _unset
          ? this.colBooleanArray
          : colBooleanArray as List<bool>?,
      colBit: colBit == _unset ? this.colBit : colBit as String?,
      colBitArray: colBitArray == _unset
          ? this.colBitArray
          : colBitArray as List<String>?,
      colBitvarying: colBitvarying == _unset
          ? this.colBitvarying
          : colBitvarying as String?,
      colBitvaryingArray: colBitvaryingArray == _unset
          ? this.colBitvaryingArray
          : colBitvaryingArray as List<String>?,
    );
  }
}
