// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class DatetimeTypes implements SupadartClass<DatetimeTypes> {
  final String id;
  final DateTime? colDate;
  final List<DateTime>? colDateArray;
  final DateTime? colTime;
  final List<DateTime>? colTimeArray;
  final DateTime? colTimetz;
  final List<DateTime>? colTimetzArray;
  final DateTime? colTimestamp;
  final List<DateTime>? colTimestampArray;
  final DateTime? colTimestamptz;
  final List<DateTime>? colTimestamptzArray;
  final Duration? colInterval;
  final List<Duration>? colIntervalArray;

  const DatetimeTypes({
    required this.id,
    this.colDate,
    this.colDateArray,
    this.colTime,
    this.colTimeArray,
    this.colTimetz,
    this.colTimetzArray,
    this.colTimestamp,
    this.colTimestampArray,
    this.colTimestamptz,
    this.colTimestamptzArray,
    this.colInterval,
    this.colIntervalArray,
  });

  static String get schema_name => 'public';
  static String get table_name => 'datetime_types';
  static String get c_id => 'id';
  static String get c_colDate => 'col_date';
  static String get c_colDateArray => 'col_date_array';
  static String get c_colTime => 'col_time';
  static String get c_colTimeArray => 'col_time_array';
  static String get c_colTimetz => 'col_timetz';
  static String get c_colTimetzArray => 'col_timetz_array';
  static String get c_colTimestamp => 'col_timestamp';
  static String get c_colTimestampArray => 'col_timestamp_array';
  static String get c_colTimestamptz => 'col_timestamptz';
  static String get c_colTimestamptzArray => 'col_timestamptz_array';
  static String get c_colInterval => 'col_interval';
  static String get c_colIntervalArray => 'col_interval_array';

  static List<DatetimeTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(DatetimeTypes.fromJson).toList();
  }

  static DatetimeTypes converterSingle(Map<String, dynamic> data) {
    return DatetimeTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    DateTime? colDate,
    List<DateTime>? colDateArray,
    DateTime? colTime,
    List<DateTime>? colTimeArray,
    DateTime? colTimetz,
    List<DateTime>? colTimetzArray,
    DateTime? colTimestamp,
    List<DateTime>? colTimestampArray,
    DateTime? colTimestamptz,
    List<DateTime>? colTimestamptzArray,
    Duration? colInterval,
    List<Duration>? colIntervalArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colDate != null) 'col_date': colDate.toIso8601String(),
      if (colDateArray != null)
        'col_date_array': colDateArray.map((e) => e.toIso8601String()).toList(),
      if (colTime != null)
        'col_time': DateFormat('HH:mm:ss.SSS').format(colTime),
      if (colTimeArray != null)
        'col_time_array': colTimeArray
            .map((e) => DateFormat('HH:mm:ss.SSS').format(e))
            .toList(),
      if (colTimetz != null)
        'col_timetz': DateFormat('HH:mm:ssZ').format(colTimetz.toLocal()),
      if (colTimetzArray != null)
        'col_timetz_array': colTimetzArray
            .map((e) => DateFormat('HH:mm:ssZ').format(e.toLocal()))
            .toList(),
      if (colTimestamp != null) 'col_timestamp': colTimestamp.toIso8601String(),
      if (colTimestampArray != null)
        'col_timestamp_array':
            colTimestampArray.map((e) => e.toIso8601String()).toList(),
      if (colTimestamptz != null)
        'col_timestamptz': colTimestamptz.toUtc().toIso8601String(),
      if (colTimestamptzArray != null)
        'col_timestamptz_array': colTimestamptzArray
            .map((e) => e.toUtc().toIso8601String())
            .toList(),
      if (colInterval != null) 'col_interval': colInterval.toString(),
      if (colIntervalArray != null)
        'col_interval_array':
            colIntervalArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    DateTime? colDate,
    List<DateTime>? colDateArray,
    DateTime? colTime,
    List<DateTime>? colTimeArray,
    DateTime? colTimetz,
    List<DateTime>? colTimetzArray,
    DateTime? colTimestamp,
    List<DateTime>? colTimestampArray,
    DateTime? colTimestamptz,
    List<DateTime>? colTimestamptzArray,
    Duration? colInterval,
    List<Duration>? colIntervalArray,
  }) {
    return _generateMap(
      id: id,
      colDate: colDate,
      colDateArray: colDateArray,
      colTime: colTime,
      colTimeArray: colTimeArray,
      colTimetz: colTimetz,
      colTimetzArray: colTimetzArray,
      colTimestamp: colTimestamp,
      colTimestampArray: colTimestampArray,
      colTimestamptz: colTimestamptz,
      colTimestamptzArray: colTimestamptzArray,
      colInterval: colInterval,
      colIntervalArray: colIntervalArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    DateTime? colDate,
    List<DateTime>? colDateArray,
    DateTime? colTime,
    List<DateTime>? colTimeArray,
    DateTime? colTimetz,
    List<DateTime>? colTimetzArray,
    DateTime? colTimestamp,
    List<DateTime>? colTimestampArray,
    DateTime? colTimestamptz,
    List<DateTime>? colTimestamptzArray,
    Duration? colInterval,
    List<Duration>? colIntervalArray,
  }) {
    return _generateMap(
      id: id,
      colDate: colDate,
      colDateArray: colDateArray,
      colTime: colTime,
      colTimeArray: colTimeArray,
      colTimetz: colTimetz,
      colTimetzArray: colTimetzArray,
      colTimestamp: colTimestamp,
      colTimestampArray: colTimestampArray,
      colTimestamptz: colTimestamptz,
      colTimestamptzArray: colTimestamptzArray,
      colInterval: colInterval,
      colIntervalArray: colIntervalArray,
    );
  }

  factory DatetimeTypes.fromJson(Map<String, dynamic> jsonn) {
    return DatetimeTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colDate: jsonn['col_date'] != null
          ? DateTime.parse(jsonn['col_date'].toString())
          : null,
      colDateArray: jsonn['col_date_array'] != null
          ? (jsonn['col_date_array'] as List<dynamic>)
              .map((v) => DateTime.parse(v.toString()))
              .toList()
          : null,
      colTime: jsonn['col_time'] != null
          ? DateTime.parse("1970-01-01T${jsonn['col_time']}").toLocal()
          : null,
      colTimeArray: jsonn['col_time_array'] != null
          ? (jsonn['col_time_array'] as List<dynamic>)
              .map((v) => DateTime.parse("1970-01-01T$v").toLocal())
              .toList()
          : null,
      colTimetz: jsonn['col_timetz'] != null
          ? DateTime.parse("1970-01-01T${jsonn['col_timetz']}").toLocal()
          : null,
      colTimetzArray: jsonn['col_timetz_array'] != null
          ? (jsonn['col_timetz_array'] as List<dynamic>)
              .map((v) => DateTime.parse("1970-01-01T$v").toLocal())
              .toList()
          : null,
      colTimestamp: jsonn['col_timestamp'] != null
          ? DateTime.parse(jsonn['col_timestamp'].toString())
          : null,
      colTimestampArray: jsonn['col_timestamp_array'] != null
          ? (jsonn['col_timestamp_array'] as List<dynamic>)
              .map((v) => DateTime.parse(v.toString()))
              .toList()
          : null,
      colTimestamptz: jsonn['col_timestamptz'] != null
          ? DateTime.parse(jsonn['col_timestamptz'].toString())
          : null,
      colTimestamptzArray: jsonn['col_timestamptz_array'] != null
          ? (jsonn['col_timestamptz_array'] as List<dynamic>)
              .map((v) => DateTime.parse(v.toString()))
              .toList()
          : null,
      colInterval: jsonn['col_interval'] != null
          ? DurationFromString.fromString(jsonn['col_interval'].toString())
          : null,
      colIntervalArray: jsonn['col_interval_array'] != null
          ? (jsonn['col_interval_array'] as List<dynamic>)
              .map((v) => DurationFromString.fromString(v.toString()))
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    DateTime? colDate,
    List<DateTime>? colDateArray,
    DateTime? colTime,
    List<DateTime>? colTimeArray,
    DateTime? colTimetz,
    List<DateTime>? colTimetzArray,
    DateTime? colTimestamp,
    List<DateTime>? colTimestampArray,
    DateTime? colTimestamptz,
    List<DateTime>? colTimestamptzArray,
    Duration? colInterval,
    List<Duration>? colIntervalArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colDate != null) 'col_date': colDate,
      if (colDateArray != null) 'col_date_array': colDateArray,
      if (colTime != null) 'col_time': colTime,
      if (colTimeArray != null) 'col_time_array': colTimeArray,
      if (colTimetz != null) 'col_timetz': colTimetz,
      if (colTimetzArray != null) 'col_timetz_array': colTimetzArray,
      if (colTimestamp != null) 'col_timestamp': colTimestamp,
      if (colTimestampArray != null) 'col_timestamp_array': colTimestampArray,
      if (colTimestamptz != null) 'col_timestamptz': colTimestamptz,
      if (colTimestamptzArray != null)
        'col_timestamptz_array': colTimestamptzArray,
      if (colInterval != null) 'col_interval': colInterval,
      if (colIntervalArray != null) 'col_interval_array': colIntervalArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colDate: colDate,
      colDateArray: colDateArray,
      colTime: colTime,
      colTimeArray: colTimeArray,
      colTimetz: colTimetz,
      colTimetzArray: colTimetzArray,
      colTimestamp: colTimestamp,
      colTimestampArray: colTimestampArray,
      colTimestamptz: colTimestamptz,
      colTimestamptzArray: colTimestamptzArray,
      colInterval: colInterval,
      colIntervalArray: colIntervalArray,
    );
  }

  static const _unset = Object();
  DatetimeTypes copyWith({
    Object? id = _unset,
    Object? colDate = _unset,
    Object? colDateArray = _unset,
    Object? colTime = _unset,
    Object? colTimeArray = _unset,
    Object? colTimetz = _unset,
    Object? colTimetzArray = _unset,
    Object? colTimestamp = _unset,
    Object? colTimestampArray = _unset,
    Object? colTimestamptz = _unset,
    Object? colTimestamptzArray = _unset,
    Object? colInterval = _unset,
    Object? colIntervalArray = _unset,
  }) {
    return DatetimeTypes(
      id: id == _unset ? this.id : id as String,
      colDate: colDate == _unset ? this.colDate : colDate as DateTime?,
      colDateArray: colDateArray == _unset
          ? this.colDateArray
          : colDateArray as List<DateTime>?,
      colTime: colTime == _unset ? this.colTime : colTime as DateTime?,
      colTimeArray: colTimeArray == _unset
          ? this.colTimeArray
          : colTimeArray as List<DateTime>?,
      colTimetz: colTimetz == _unset ? this.colTimetz : colTimetz as DateTime?,
      colTimetzArray: colTimetzArray == _unset
          ? this.colTimetzArray
          : colTimetzArray as List<DateTime>?,
      colTimestamp: colTimestamp == _unset
          ? this.colTimestamp
          : colTimestamp as DateTime?,
      colTimestampArray: colTimestampArray == _unset
          ? this.colTimestampArray
          : colTimestampArray as List<DateTime>?,
      colTimestamptz: colTimestamptz == _unset
          ? this.colTimestamptz
          : colTimestamptz as DateTime?,
      colTimestamptzArray: colTimestamptzArray == _unset
          ? this.colTimestamptzArray
          : colTimestamptzArray as List<DateTime>?,
      colInterval:
          colInterval == _unset ? this.colInterval : colInterval as Duration?,
      colIntervalArray: colIntervalArray == _unset
          ? this.colIntervalArray
          : colIntervalArray as List<Duration>?,
    );
  }
}
