// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Embeddings implements SupadartClass<Embeddings> {
  final String? embedding;

  const Embeddings({
    this.embedding,
  });

  static String get table_name => 'embeddings';
  static String get c_embedding => 'embedding';

  static List<Embeddings> converter(List<Map<String, dynamic>> data) {
    return data.map(Embeddings.fromJson).toList();
  }

  static Embeddings converterSingle(Map<String, dynamic> data) {
    return Embeddings.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? embedding,
  }) {
    return {
      if (embedding != null) 'embedding': embedding.toString(),
    };
  }

  static Map<String, dynamic> insert({
    String? embedding,
  }) {
    return _generateMap(
      embedding: embedding,
    );
  }

  static Map<String, dynamic> update({
    String? embedding,
  }) {
    return _generateMap(
      embedding: embedding,
    );
  }

  factory Embeddings.fromJson(Map<String, dynamic> jsonn) {
    return Embeddings(
      embedding:
          jsonn['embedding'] != null ? jsonn['embedding'].toString() : null,
    );
  }

  static Object New({
    String? embedding,
  }) {
    return {
      if (embedding != null) 'embedding': embedding,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      embedding: embedding,
    );
  }

  static const _unset = Object();
  Embeddings copyWith({
    Object? embedding = _unset,
  }) {
    return Embeddings(
      embedding: embedding == _unset ? this.embedding : embedding as String?,
    );
  }
}
