// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class EnumTypes implements SupadartClass<EnumTypes> {
  final String id;
  final MOOD colMood;
  final List<MOOD> colMoodArray;

  const EnumTypes({
    required this.id,
    required this.colMood,
    required this.colMoodArray,
  });

  static String get table_name => 'enum_types';
  static String get c_id => 'id';
  static String get c_colMood => 'col_mood';
  static String get c_colMoodArray => 'col_mood_array';

  static List<EnumTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(EnumTypes.fromJson).toList();
  }

  static EnumTypes converterSingle(Map<String, dynamic> data) {
    return EnumTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    MOOD? colMood,
    List<MOOD>? colMoodArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colMood != null) 'col_mood': colMood.value,
      if (colMoodArray != null)
        'col_mood_array': colMoodArray.map((e) => e.value).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required MOOD colMood,
    required List<MOOD> colMoodArray,
  }) {
    return _generateMap(
      id: id,
      colMood: colMood,
      colMoodArray: colMoodArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    MOOD? colMood,
    List<MOOD>? colMoodArray,
  }) {
    return _generateMap(
      id: id,
      colMood: colMood,
      colMoodArray: colMoodArray,
    );
  }

  factory EnumTypes.fromJson(Map<String, dynamic> jsonn) {
    return EnumTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colMood: jsonn['col_mood'] != null
          ? MOOD.fromValue(jsonn['col_mood'].toString())
          : MOOD.values.first,
      colMoodArray: jsonn['col_mood_array'] != null
          ? (jsonn['col_mood_array'] as List<dynamic>)
              .map((e) => MOOD.fromValue(e.toString()))
              .toList()
          : <MOOD>[],
    );
  }

  static Object New({
    String? id,
    MOOD? colMood,
    List<MOOD>? colMoodArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colMood != null) 'col_mood': colMood,
      if (colMoodArray != null) 'col_mood_array': colMoodArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colMood: colMood,
      colMoodArray: colMoodArray,
    );
  }

  static const _unset = Object();
  EnumTypes copyWith({
    Object? id = _unset,
    Object? colMood = _unset,
    Object? colMoodArray = _unset,
  }) {
    return EnumTypes(
      id: id == _unset ? this.id : id as String,
      colMood: colMood == _unset ? this.colMood : colMood as MOOD,
      colMoodArray: colMoodArray == _unset
          ? this.colMoodArray
          : colMoodArray as List<MOOD>,
    );
  }
}
