// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class EnumLabelTypes implements SupadartClass<EnumLabelTypes> {
  final String id;
  final TASK_STATUS colStatus;
  final TASK_STATUS? colStatusNullable;
  final List<TASK_STATUS>? colStatusArray;

  const EnumLabelTypes({
    required this.id,
    required this.colStatus,
    this.colStatusNullable,
    this.colStatusArray,
  });

  static String get table_name => 'enum_label_types';
  static String get c_id => 'id';
  static String get c_colStatus => 'col_status';
  static String get c_colStatusNullable => 'col_status_nullable';
  static String get c_colStatusArray => 'col_status_array';

  static List<EnumLabelTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(EnumLabelTypes.fromJson).toList();
  }

  static EnumLabelTypes converterSingle(Map<String, dynamic> data) {
    return EnumLabelTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    TASK_STATUS? colStatus,
    TASK_STATUS? colStatusNullable,
    List<TASK_STATUS>? colStatusArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colStatus != null) 'col_status': colStatus.value,
      if (colStatusNullable != null)
        'col_status_nullable': colStatusNullable.value,
      if (colStatusArray != null)
        'col_status_array': colStatusArray.map((e) => e.value).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required TASK_STATUS colStatus,
    TASK_STATUS? colStatusNullable,
    List<TASK_STATUS>? colStatusArray,
  }) {
    return _generateMap(
      id: id,
      colStatus: colStatus,
      colStatusNullable: colStatusNullable,
      colStatusArray: colStatusArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    TASK_STATUS? colStatus,
    TASK_STATUS? colStatusNullable,
    List<TASK_STATUS>? colStatusArray,
  }) {
    return _generateMap(
      id: id,
      colStatus: colStatus,
      colStatusNullable: colStatusNullable,
      colStatusArray: colStatusArray,
    );
  }

  factory EnumLabelTypes.fromJson(Map<String, dynamic> jsonn) {
    return EnumLabelTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colStatus: jsonn['col_status'] != null
          ? TASK_STATUS.fromValue(jsonn['col_status'].toString())
          : TASK_STATUS.values.first,
      colStatusNullable: jsonn['col_status_nullable'] != null
          ? TASK_STATUS.fromValue(jsonn['col_status_nullable'].toString())
          : null,
      colStatusArray: jsonn['col_status_array'] != null
          ? (jsonn['col_status_array'] as List<dynamic>)
              .map((e) => TASK_STATUS.fromValue(e.toString()))
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    TASK_STATUS? colStatus,
    TASK_STATUS? colStatusNullable,
    List<TASK_STATUS>? colStatusArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colStatus != null) 'col_status': colStatus,
      if (colStatusNullable != null) 'col_status_nullable': colStatusNullable,
      if (colStatusArray != null) 'col_status_array': colStatusArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colStatus: colStatus,
      colStatusNullable: colStatusNullable,
      colStatusArray: colStatusArray,
    );
  }

  static const _unset = Object();
  EnumLabelTypes copyWith({
    Object? id = _unset,
    Object? colStatus = _unset,
    Object? colStatusNullable = _unset,
    Object? colStatusArray = _unset,
  }) {
    return EnumLabelTypes(
      id: id == _unset ? this.id : id as String,
      colStatus:
          colStatus == _unset ? this.colStatus : colStatus as TASK_STATUS,
      colStatusNullable: colStatusNullable == _unset
          ? this.colStatusNullable
          : colStatusNullable as TASK_STATUS?,
      colStatusArray: colStatusArray == _unset
          ? this.colStatusArray
          : colStatusArray as List<TASK_STATUS>?,
    );
  }
}
