// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class GeometricTypes implements SupadartClass<GeometricTypes> {
  final String id;
  final String? colPoint;
  final List<String>? colPointArray;
  final String? colLine;
  final List<String>? colLineArray;
  final String? colLseg;
  final List<String>? colLsegArray;
  final String? colBox;
  final List<String>? colBoxArray;
  final String? colPath;
  final List<String>? colPathArray;
  final String? colPolygon;
  final List<String>? colPolygonArray;
  final String? colCircle;
  final List<String>? colCircleArray;

  const GeometricTypes({
    required this.id,
    this.colPoint,
    this.colPointArray,
    this.colLine,
    this.colLineArray,
    this.colLseg,
    this.colLsegArray,
    this.colBox,
    this.colBoxArray,
    this.colPath,
    this.colPathArray,
    this.colPolygon,
    this.colPolygonArray,
    this.colCircle,
    this.colCircleArray,
  });

  static String get schema_name => 'public';
  static String get table_name => 'geometric_types';
  static String get c_id => 'id';
  static String get c_colPoint => 'col_point';
  static String get c_colPointArray => 'col_point_array';
  static String get c_colLine => 'col_line';
  static String get c_colLineArray => 'col_line_array';
  static String get c_colLseg => 'col_lseg';
  static String get c_colLsegArray => 'col_lseg_array';
  static String get c_colBox => 'col_box';
  static String get c_colBoxArray => 'col_box_array';
  static String get c_colPath => 'col_path';
  static String get c_colPathArray => 'col_path_array';
  static String get c_colPolygon => 'col_polygon';
  static String get c_colPolygonArray => 'col_polygon_array';
  static String get c_colCircle => 'col_circle';
  static String get c_colCircleArray => 'col_circle_array';

  static List<GeometricTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(GeometricTypes.fromJson).toList();
  }

  static GeometricTypes converterSingle(Map<String, dynamic> data) {
    return GeometricTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? colPoint,
    List<String>? colPointArray,
    String? colLine,
    List<String>? colLineArray,
    String? colLseg,
    List<String>? colLsegArray,
    String? colBox,
    List<String>? colBoxArray,
    String? colPath,
    List<String>? colPathArray,
    String? colPolygon,
    List<String>? colPolygonArray,
    String? colCircle,
    List<String>? colCircleArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colPoint != null) 'col_point': colPoint.toString(),
      if (colPointArray != null)
        'col_point_array': colPointArray.map((e) => e.toString()).toList(),
      if (colLine != null) 'col_line': colLine.toString(),
      if (colLineArray != null)
        'col_line_array': colLineArray.map((e) => e.toString()).toList(),
      if (colLseg != null) 'col_lseg': colLseg.toString(),
      if (colLsegArray != null)
        'col_lseg_array': colLsegArray.map((e) => e.toString()).toList(),
      if (colBox != null) 'col_box': colBox.toString(),
      if (colBoxArray != null)
        'col_box_array': colBoxArray.map((e) => e.toString()).toList(),
      if (colPath != null) 'col_path': colPath.toString(),
      if (colPathArray != null)
        'col_path_array': colPathArray.map((e) => e.toString()).toList(),
      if (colPolygon != null) 'col_polygon': colPolygon.toString(),
      if (colPolygonArray != null)
        'col_polygon_array': colPolygonArray.map((e) => e.toString()).toList(),
      if (colCircle != null) 'col_circle': colCircle.toString(),
      if (colCircleArray != null)
        'col_circle_array': colCircleArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? colPoint,
    List<String>? colPointArray,
    String? colLine,
    List<String>? colLineArray,
    String? colLseg,
    List<String>? colLsegArray,
    String? colBox,
    List<String>? colBoxArray,
    String? colPath,
    List<String>? colPathArray,
    String? colPolygon,
    List<String>? colPolygonArray,
    String? colCircle,
    List<String>? colCircleArray,
  }) {
    return _generateMap(
      id: id,
      colPoint: colPoint,
      colPointArray: colPointArray,
      colLine: colLine,
      colLineArray: colLineArray,
      colLseg: colLseg,
      colLsegArray: colLsegArray,
      colBox: colBox,
      colBoxArray: colBoxArray,
      colPath: colPath,
      colPathArray: colPathArray,
      colPolygon: colPolygon,
      colPolygonArray: colPolygonArray,
      colCircle: colCircle,
      colCircleArray: colCircleArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? colPoint,
    List<String>? colPointArray,
    String? colLine,
    List<String>? colLineArray,
    String? colLseg,
    List<String>? colLsegArray,
    String? colBox,
    List<String>? colBoxArray,
    String? colPath,
    List<String>? colPathArray,
    String? colPolygon,
    List<String>? colPolygonArray,
    String? colCircle,
    List<String>? colCircleArray,
  }) {
    return _generateMap(
      id: id,
      colPoint: colPoint,
      colPointArray: colPointArray,
      colLine: colLine,
      colLineArray: colLineArray,
      colLseg: colLseg,
      colLsegArray: colLsegArray,
      colBox: colBox,
      colBoxArray: colBoxArray,
      colPath: colPath,
      colPathArray: colPathArray,
      colPolygon: colPolygon,
      colPolygonArray: colPolygonArray,
      colCircle: colCircle,
      colCircleArray: colCircleArray,
    );
  }

  factory GeometricTypes.fromJson(Map<String, dynamic> jsonn) {
    return GeometricTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colPoint:
          jsonn['col_point'] != null ? jsonn['col_point'].toString() : null,
      colPointArray: jsonn['col_point_array'] != null
          ? (jsonn['col_point_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colLine: jsonn['col_line'] != null ? jsonn['col_line'].toString() : null,
      colLineArray: jsonn['col_line_array'] != null
          ? (jsonn['col_line_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colLseg: jsonn['col_lseg'] != null ? jsonn['col_lseg'].toString() : null,
      colLsegArray: jsonn['col_lseg_array'] != null
          ? (jsonn['col_lseg_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colBox: jsonn['col_box'] != null ? jsonn['col_box'].toString() : null,
      colBoxArray: jsonn['col_box_array'] != null
          ? (jsonn['col_box_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colPath: jsonn['col_path'] != null ? jsonn['col_path'].toString() : null,
      colPathArray: jsonn['col_path_array'] != null
          ? (jsonn['col_path_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colPolygon:
          jsonn['col_polygon'] != null ? jsonn['col_polygon'].toString() : null,
      colPolygonArray: jsonn['col_polygon_array'] != null
          ? (jsonn['col_polygon_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colCircle:
          jsonn['col_circle'] != null ? jsonn['col_circle'].toString() : null,
      colCircleArray: jsonn['col_circle_array'] != null
          ? (jsonn['col_circle_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    String? colPoint,
    List<String>? colPointArray,
    String? colLine,
    List<String>? colLineArray,
    String? colLseg,
    List<String>? colLsegArray,
    String? colBox,
    List<String>? colBoxArray,
    String? colPath,
    List<String>? colPathArray,
    String? colPolygon,
    List<String>? colPolygonArray,
    String? colCircle,
    List<String>? colCircleArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colPoint != null) 'col_point': colPoint,
      if (colPointArray != null) 'col_point_array': colPointArray,
      if (colLine != null) 'col_line': colLine,
      if (colLineArray != null) 'col_line_array': colLineArray,
      if (colLseg != null) 'col_lseg': colLseg,
      if (colLsegArray != null) 'col_lseg_array': colLsegArray,
      if (colBox != null) 'col_box': colBox,
      if (colBoxArray != null) 'col_box_array': colBoxArray,
      if (colPath != null) 'col_path': colPath,
      if (colPathArray != null) 'col_path_array': colPathArray,
      if (colPolygon != null) 'col_polygon': colPolygon,
      if (colPolygonArray != null) 'col_polygon_array': colPolygonArray,
      if (colCircle != null) 'col_circle': colCircle,
      if (colCircleArray != null) 'col_circle_array': colCircleArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colPoint: colPoint,
      colPointArray: colPointArray,
      colLine: colLine,
      colLineArray: colLineArray,
      colLseg: colLseg,
      colLsegArray: colLsegArray,
      colBox: colBox,
      colBoxArray: colBoxArray,
      colPath: colPath,
      colPathArray: colPathArray,
      colPolygon: colPolygon,
      colPolygonArray: colPolygonArray,
      colCircle: colCircle,
      colCircleArray: colCircleArray,
    );
  }

  static const _unset = Object();
  GeometricTypes copyWith({
    Object? id = _unset,
    Object? colPoint = _unset,
    Object? colPointArray = _unset,
    Object? colLine = _unset,
    Object? colLineArray = _unset,
    Object? colLseg = _unset,
    Object? colLsegArray = _unset,
    Object? colBox = _unset,
    Object? colBoxArray = _unset,
    Object? colPath = _unset,
    Object? colPathArray = _unset,
    Object? colPolygon = _unset,
    Object? colPolygonArray = _unset,
    Object? colCircle = _unset,
    Object? colCircleArray = _unset,
  }) {
    return GeometricTypes(
      id: id == _unset ? this.id : id as String,
      colPoint: colPoint == _unset ? this.colPoint : colPoint as String?,
      colPointArray: colPointArray == _unset
          ? this.colPointArray
          : colPointArray as List<String>?,
      colLine: colLine == _unset ? this.colLine : colLine as String?,
      colLineArray: colLineArray == _unset
          ? this.colLineArray
          : colLineArray as List<String>?,
      colLseg: colLseg == _unset ? this.colLseg : colLseg as String?,
      colLsegArray: colLsegArray == _unset
          ? this.colLsegArray
          : colLsegArray as List<String>?,
      colBox: colBox == _unset ? this.colBox : colBox as String?,
      colBoxArray: colBoxArray == _unset
          ? this.colBoxArray
          : colBoxArray as List<String>?,
      colPath: colPath == _unset ? this.colPath : colPath as String?,
      colPathArray: colPathArray == _unset
          ? this.colPathArray
          : colPathArray as List<String>?,
      colPolygon:
          colPolygon == _unset ? this.colPolygon : colPolygon as String?,
      colPolygonArray: colPolygonArray == _unset
          ? this.colPolygonArray
          : colPolygonArray as List<String>?,
      colCircle: colCircle == _unset ? this.colCircle : colCircle as String?,
      colCircleArray: colCircleArray == _unset
          ? this.colCircleArray
          : colCircleArray as List<String>?,
    );
  }
}
