// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class JsonTypes implements SupadartClass<JsonTypes> {
  final String id;
  final Map<String, dynamic>? colJson;
  final List<Map<String, dynamic>>? colJsonArray;
  final Map<String, dynamic>? colJsonb;
  final List<Map<String, dynamic>>? colJsonbArray;

  const JsonTypes({
    required this.id,
    this.colJson,
    this.colJsonArray,
    this.colJsonb,
    this.colJsonbArray,
  });

  static String get table_name => 'json_types';
  static String get c_id => 'id';
  static String get c_colJson => 'col_json';
  static String get c_colJsonArray => 'col_json_array';
  static String get c_colJsonb => 'col_jsonb';
  static String get c_colJsonbArray => 'col_jsonb_array';

  static List<JsonTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(JsonTypes.fromJson).toList();
  }

  static JsonTypes converterSingle(Map<String, dynamic> data) {
    return JsonTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    Map<String, dynamic>? colJson,
    List<Map<String, dynamic>>? colJsonArray,
    Map<String, dynamic>? colJsonb,
    List<Map<String, dynamic>>? colJsonbArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colJson != null) 'col_json': colJson,
      if (colJsonArray != null) 'col_json_array': colJsonArray,
      if (colJsonb != null) 'col_jsonb': colJsonb,
      if (colJsonbArray != null) 'col_jsonb_array': colJsonbArray,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    Map<String, dynamic>? colJson,
    List<Map<String, dynamic>>? colJsonArray,
    Map<String, dynamic>? colJsonb,
    List<Map<String, dynamic>>? colJsonbArray,
  }) {
    return _generateMap(
      id: id,
      colJson: colJson,
      colJsonArray: colJsonArray,
      colJsonb: colJsonb,
      colJsonbArray: colJsonbArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    Map<String, dynamic>? colJson,
    List<Map<String, dynamic>>? colJsonArray,
    Map<String, dynamic>? colJsonb,
    List<Map<String, dynamic>>? colJsonbArray,
  }) {
    return _generateMap(
      id: id,
      colJson: colJson,
      colJsonArray: colJsonArray,
      colJsonb: colJsonb,
      colJsonbArray: colJsonbArray,
    );
  }

  factory JsonTypes.fromJson(Map<String, dynamic> jsonn) {
    return JsonTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colJson: jsonn['col_json'] != null
          ? jsonn['col_json'] as Map<String, dynamic>
          : null,
      colJsonArray: jsonn['col_json_array'] != null
          ? (jsonn['col_json_array'] as List<dynamic>)
              .map((v) =>
                  (v is String ? json.decode(v) : v) as Map<String, dynamic>)
              .toList()
          : null,
      colJsonb: jsonn['col_jsonb'] != null
          ? jsonn['col_jsonb'] as Map<String, dynamic>
          : null,
      colJsonbArray: jsonn['col_jsonb_array'] != null
          ? (jsonn['col_jsonb_array'] as List<dynamic>)
              .map((v) =>
                  (v is String ? json.decode(v) : v) as Map<String, dynamic>)
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    Map<String, dynamic>? colJson,
    List<Map<String, dynamic>>? colJsonArray,
    Map<String, dynamic>? colJsonb,
    List<Map<String, dynamic>>? colJsonbArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colJson != null) 'col_json': colJson,
      if (colJsonArray != null) 'col_json_array': colJsonArray,
      if (colJsonb != null) 'col_jsonb': colJsonb,
      if (colJsonbArray != null) 'col_jsonb_array': colJsonbArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colJson: colJson,
      colJsonArray: colJsonArray,
      colJsonb: colJsonb,
      colJsonbArray: colJsonbArray,
    );
  }

  static const _unset = Object();
  JsonTypes copyWith({
    Object? id = _unset,
    Object? colJson = _unset,
    Object? colJsonArray = _unset,
    Object? colJsonb = _unset,
    Object? colJsonbArray = _unset,
  }) {
    return JsonTypes(
      id: id == _unset ? this.id : id as String,
      colJson:
          colJson == _unset ? this.colJson : colJson as Map<String, dynamic>?,
      colJsonArray: colJsonArray == _unset
          ? this.colJsonArray
          : colJsonArray as List<Map<String, dynamic>>?,
      colJsonb: colJsonb == _unset
          ? this.colJsonb
          : colJsonb as Map<String, dynamic>?,
      colJsonbArray: colJsonbArray == _unset
          ? this.colJsonbArray
          : colJsonbArray as List<Map<String, dynamic>>?,
    );
  }
}
