// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class MiscTypes implements SupadartClass<MiscTypes> {
  final String id;
  final String? colMoney;
  final List<String>? colMoneyArray;
  final String? colPgLsn;
  final List<String>? colPgLsnArray;
  final String? colPgSnapshot;
  final List<String>? colPgSnapshotArray;
  final String? colTsquery;
  final List<String>? colTsqueryArray;
  final String? colTsvector;
  final List<String>? colTsvectorArray;
  final String? colTxidSnapshot;
  final List<String>? colTxidSnapshotArray;

  const MiscTypes({
    required this.id,
    this.colMoney,
    this.colMoneyArray,
    this.colPgLsn,
    this.colPgLsnArray,
    this.colPgSnapshot,
    this.colPgSnapshotArray,
    this.colTsquery,
    this.colTsqueryArray,
    this.colTsvector,
    this.colTsvectorArray,
    this.colTxidSnapshot,
    this.colTxidSnapshotArray,
  });

  static String get table_name => 'misc_types';
  static String get c_id => 'id';
  static String get c_colMoney => 'col_money';
  static String get c_colMoneyArray => 'col_money_array';
  static String get c_colPgLsn => 'col_pg_lsn';
  static String get c_colPgLsnArray => 'col_pg_lsn_array';
  static String get c_colPgSnapshot => 'col_pg_snapshot';
  static String get c_colPgSnapshotArray => 'col_pg_snapshot_array';
  static String get c_colTsquery => 'col_tsquery';
  static String get c_colTsqueryArray => 'col_tsquery_array';
  static String get c_colTsvector => 'col_tsvector';
  static String get c_colTsvectorArray => 'col_tsvector_array';
  static String get c_colTxidSnapshot => 'col_txid_snapshot';
  static String get c_colTxidSnapshotArray => 'col_txid_snapshot_array';

  static List<MiscTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(MiscTypes.fromJson).toList();
  }

  static MiscTypes converterSingle(Map<String, dynamic> data) {
    return MiscTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? colMoney,
    List<String>? colMoneyArray,
    String? colPgLsn,
    List<String>? colPgLsnArray,
    String? colPgSnapshot,
    List<String>? colPgSnapshotArray,
    String? colTsquery,
    List<String>? colTsqueryArray,
    String? colTsvector,
    List<String>? colTsvectorArray,
    String? colTxidSnapshot,
    List<String>? colTxidSnapshotArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colMoney != null) 'col_money': colMoney.toString(),
      if (colMoneyArray != null)
        'col_money_array': colMoneyArray.map((e) => e.toString()).toList(),
      if (colPgLsn != null) 'col_pg_lsn': colPgLsn.toString(),
      if (colPgLsnArray != null)
        'col_pg_lsn_array': colPgLsnArray.map((e) => e.toString()).toList(),
      if (colPgSnapshot != null) 'col_pg_snapshot': colPgSnapshot.toString(),
      if (colPgSnapshotArray != null)
        'col_pg_snapshot_array':
            colPgSnapshotArray.map((e) => e.toString()).toList(),
      if (colTsquery != null) 'col_tsquery': colTsquery.toString(),
      if (colTsqueryArray != null)
        'col_tsquery_array': colTsqueryArray.map((e) => e.toString()).toList(),
      if (colTsvector != null) 'col_tsvector': colTsvector.toString(),
      if (colTsvectorArray != null)
        'col_tsvector_array':
            colTsvectorArray.map((e) => e.toString()).toList(),
      if (colTxidSnapshot != null)
        'col_txid_snapshot': colTxidSnapshot.toString(),
      if (colTxidSnapshotArray != null)
        'col_txid_snapshot_array':
            colTxidSnapshotArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? colMoney,
    List<String>? colMoneyArray,
    String? colPgLsn,
    List<String>? colPgLsnArray,
    String? colPgSnapshot,
    List<String>? colPgSnapshotArray,
    String? colTsquery,
    List<String>? colTsqueryArray,
    String? colTsvector,
    List<String>? colTsvectorArray,
    String? colTxidSnapshot,
    List<String>? colTxidSnapshotArray,
  }) {
    return _generateMap(
      id: id,
      colMoney: colMoney,
      colMoneyArray: colMoneyArray,
      colPgLsn: colPgLsn,
      colPgLsnArray: colPgLsnArray,
      colPgSnapshot: colPgSnapshot,
      colPgSnapshotArray: colPgSnapshotArray,
      colTsquery: colTsquery,
      colTsqueryArray: colTsqueryArray,
      colTsvector: colTsvector,
      colTsvectorArray: colTsvectorArray,
      colTxidSnapshot: colTxidSnapshot,
      colTxidSnapshotArray: colTxidSnapshotArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? colMoney,
    List<String>? colMoneyArray,
    String? colPgLsn,
    List<String>? colPgLsnArray,
    String? colPgSnapshot,
    List<String>? colPgSnapshotArray,
    String? colTsquery,
    List<String>? colTsqueryArray,
    String? colTsvector,
    List<String>? colTsvectorArray,
    String? colTxidSnapshot,
    List<String>? colTxidSnapshotArray,
  }) {
    return _generateMap(
      id: id,
      colMoney: colMoney,
      colMoneyArray: colMoneyArray,
      colPgLsn: colPgLsn,
      colPgLsnArray: colPgLsnArray,
      colPgSnapshot: colPgSnapshot,
      colPgSnapshotArray: colPgSnapshotArray,
      colTsquery: colTsquery,
      colTsqueryArray: colTsqueryArray,
      colTsvector: colTsvector,
      colTsvectorArray: colTsvectorArray,
      colTxidSnapshot: colTxidSnapshot,
      colTxidSnapshotArray: colTxidSnapshotArray,
    );
  }

  factory MiscTypes.fromJson(Map<String, dynamic> jsonn) {
    return MiscTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colMoney:
          jsonn['col_money'] != null ? jsonn['col_money'].toString() : null,
      colMoneyArray: jsonn['col_money_array'] != null
          ? (jsonn['col_money_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colPgLsn:
          jsonn['col_pg_lsn'] != null ? jsonn['col_pg_lsn'].toString() : null,
      colPgLsnArray: jsonn['col_pg_lsn_array'] != null
          ? (jsonn['col_pg_lsn_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colPgSnapshot: jsonn['col_pg_snapshot'] != null
          ? jsonn['col_pg_snapshot'].toString()
          : null,
      colPgSnapshotArray: jsonn['col_pg_snapshot_array'] != null
          ? (jsonn['col_pg_snapshot_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colTsquery:
          jsonn['col_tsquery'] != null ? jsonn['col_tsquery'].toString() : null,
      colTsqueryArray: jsonn['col_tsquery_array'] != null
          ? (jsonn['col_tsquery_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colTsvector: jsonn['col_tsvector'] != null
          ? jsonn['col_tsvector'].toString()
          : null,
      colTsvectorArray: jsonn['col_tsvector_array'] != null
          ? (jsonn['col_tsvector_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colTxidSnapshot: jsonn['col_txid_snapshot'] != null
          ? jsonn['col_txid_snapshot'].toString()
          : null,
      colTxidSnapshotArray: jsonn['col_txid_snapshot_array'] != null
          ? (jsonn['col_txid_snapshot_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    String? colMoney,
    List<String>? colMoneyArray,
    String? colPgLsn,
    List<String>? colPgLsnArray,
    String? colPgSnapshot,
    List<String>? colPgSnapshotArray,
    String? colTsquery,
    List<String>? colTsqueryArray,
    String? colTsvector,
    List<String>? colTsvectorArray,
    String? colTxidSnapshot,
    List<String>? colTxidSnapshotArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colMoney != null) 'col_money': colMoney,
      if (colMoneyArray != null) 'col_money_array': colMoneyArray,
      if (colPgLsn != null) 'col_pg_lsn': colPgLsn,
      if (colPgLsnArray != null) 'col_pg_lsn_array': colPgLsnArray,
      if (colPgSnapshot != null) 'col_pg_snapshot': colPgSnapshot,
      if (colPgSnapshotArray != null)
        'col_pg_snapshot_array': colPgSnapshotArray,
      if (colTsquery != null) 'col_tsquery': colTsquery,
      if (colTsqueryArray != null) 'col_tsquery_array': colTsqueryArray,
      if (colTsvector != null) 'col_tsvector': colTsvector,
      if (colTsvectorArray != null) 'col_tsvector_array': colTsvectorArray,
      if (colTxidSnapshot != null) 'col_txid_snapshot': colTxidSnapshot,
      if (colTxidSnapshotArray != null)
        'col_txid_snapshot_array': colTxidSnapshotArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colMoney: colMoney,
      colMoneyArray: colMoneyArray,
      colPgLsn: colPgLsn,
      colPgLsnArray: colPgLsnArray,
      colPgSnapshot: colPgSnapshot,
      colPgSnapshotArray: colPgSnapshotArray,
      colTsquery: colTsquery,
      colTsqueryArray: colTsqueryArray,
      colTsvector: colTsvector,
      colTsvectorArray: colTsvectorArray,
      colTxidSnapshot: colTxidSnapshot,
      colTxidSnapshotArray: colTxidSnapshotArray,
    );
  }

  static const _unset = Object();
  MiscTypes copyWith({
    Object? id = _unset,
    Object? colMoney = _unset,
    Object? colMoneyArray = _unset,
    Object? colPgLsn = _unset,
    Object? colPgLsnArray = _unset,
    Object? colPgSnapshot = _unset,
    Object? colPgSnapshotArray = _unset,
    Object? colTsquery = _unset,
    Object? colTsqueryArray = _unset,
    Object? colTsvector = _unset,
    Object? colTsvectorArray = _unset,
    Object? colTxidSnapshot = _unset,
    Object? colTxidSnapshotArray = _unset,
  }) {
    return MiscTypes(
      id: id == _unset ? this.id : id as String,
      colMoney: colMoney == _unset ? this.colMoney : colMoney as String?,
      colMoneyArray: colMoneyArray == _unset
          ? this.colMoneyArray
          : colMoneyArray as List<String>?,
      colPgLsn: colPgLsn == _unset ? this.colPgLsn : colPgLsn as String?,
      colPgLsnArray: colPgLsnArray == _unset
          ? this.colPgLsnArray
          : colPgLsnArray as List<String>?,
      colPgSnapshot: colPgSnapshot == _unset
          ? this.colPgSnapshot
          : colPgSnapshot as String?,
      colPgSnapshotArray: colPgSnapshotArray == _unset
          ? this.colPgSnapshotArray
          : colPgSnapshotArray as List<String>?,
      colTsquery:
          colTsquery == _unset ? this.colTsquery : colTsquery as String?,
      colTsqueryArray: colTsqueryArray == _unset
          ? this.colTsqueryArray
          : colTsqueryArray as List<String>?,
      colTsvector:
          colTsvector == _unset ? this.colTsvector : colTsvector as String?,
      colTsvectorArray: colTsvectorArray == _unset
          ? this.colTsvectorArray
          : colTsvectorArray as List<String>?,
      colTxidSnapshot: colTxidSnapshot == _unset
          ? this.colTxidSnapshot
          : colTxidSnapshot as String?,
      colTxidSnapshotArray: colTxidSnapshotArray == _unset
          ? this.colTxidSnapshotArray
          : colTxidSnapshotArray as List<String>?,
    );
  }
}
