// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class NetworkTypes implements SupadartClass<NetworkTypes> {
  final String id;
  final String? colCidr;
  final List<String>? colCidrArray;
  final String? colInet;
  final List<String>? colInetArray;
  final String? colMacaddr;
  final List<String>? colMacaddrArray;
  final String? colMacaddr8;
  final List<String>? colMacaddr8Array;

  const NetworkTypes({
    required this.id,
    this.colCidr,
    this.colCidrArray,
    this.colInet,
    this.colInetArray,
    this.colMacaddr,
    this.colMacaddrArray,
    this.colMacaddr8,
    this.colMacaddr8Array,
  });

  static String get schema_name => 'public';
  static String get table_name => 'network_types';
  static String get c_id => 'id';
  static String get c_colCidr => 'col_cidr';
  static String get c_colCidrArray => 'col_cidr_array';
  static String get c_colInet => 'col_inet';
  static String get c_colInetArray => 'col_inet_array';
  static String get c_colMacaddr => 'col_macaddr';
  static String get c_colMacaddrArray => 'col_macaddr_array';
  static String get c_colMacaddr8 => 'col_macaddr8';
  static String get c_colMacaddr8Array => 'col_macaddr8_array';

  static List<NetworkTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(NetworkTypes.fromJson).toList();
  }

  static NetworkTypes converterSingle(Map<String, dynamic> data) {
    return NetworkTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? colCidr,
    List<String>? colCidrArray,
    String? colInet,
    List<String>? colInetArray,
    String? colMacaddr,
    List<String>? colMacaddrArray,
    String? colMacaddr8,
    List<String>? colMacaddr8Array,
  }) {
    return {
      if (id != null) 'id': id,
      if (colCidr != null) 'col_cidr': colCidr.toString(),
      if (colCidrArray != null)
        'col_cidr_array': colCidrArray.map((e) => e.toString()).toList(),
      if (colInet != null) 'col_inet': colInet.toString(),
      if (colInetArray != null)
        'col_inet_array': colInetArray.map((e) => e.toString()).toList(),
      if (colMacaddr != null) 'col_macaddr': colMacaddr.toString(),
      if (colMacaddrArray != null)
        'col_macaddr_array': colMacaddrArray.map((e) => e.toString()).toList(),
      if (colMacaddr8 != null) 'col_macaddr8': colMacaddr8.toString(),
      if (colMacaddr8Array != null)
        'col_macaddr8_array':
            colMacaddr8Array.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? colCidr,
    List<String>? colCidrArray,
    String? colInet,
    List<String>? colInetArray,
    String? colMacaddr,
    List<String>? colMacaddrArray,
    String? colMacaddr8,
    List<String>? colMacaddr8Array,
  }) {
    return _generateMap(
      id: id,
      colCidr: colCidr,
      colCidrArray: colCidrArray,
      colInet: colInet,
      colInetArray: colInetArray,
      colMacaddr: colMacaddr,
      colMacaddrArray: colMacaddrArray,
      colMacaddr8: colMacaddr8,
      colMacaddr8Array: colMacaddr8Array,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? colCidr,
    List<String>? colCidrArray,
    String? colInet,
    List<String>? colInetArray,
    String? colMacaddr,
    List<String>? colMacaddrArray,
    String? colMacaddr8,
    List<String>? colMacaddr8Array,
  }) {
    return _generateMap(
      id: id,
      colCidr: colCidr,
      colCidrArray: colCidrArray,
      colInet: colInet,
      colInetArray: colInetArray,
      colMacaddr: colMacaddr,
      colMacaddrArray: colMacaddrArray,
      colMacaddr8: colMacaddr8,
      colMacaddr8Array: colMacaddr8Array,
    );
  }

  factory NetworkTypes.fromJson(Map<String, dynamic> jsonn) {
    return NetworkTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colCidr: jsonn['col_cidr'] != null ? jsonn['col_cidr'].toString() : null,
      colCidrArray: jsonn['col_cidr_array'] != null
          ? (jsonn['col_cidr_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colInet: jsonn['col_inet'] != null ? jsonn['col_inet'].toString() : null,
      colInetArray: jsonn['col_inet_array'] != null
          ? (jsonn['col_inet_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colMacaddr:
          jsonn['col_macaddr'] != null ? jsonn['col_macaddr'].toString() : null,
      colMacaddrArray: jsonn['col_macaddr_array'] != null
          ? (jsonn['col_macaddr_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
      colMacaddr8: jsonn['col_macaddr8'] != null
          ? jsonn['col_macaddr8'].toString()
          : null,
      colMacaddr8Array: jsonn['col_macaddr8_array'] != null
          ? (jsonn['col_macaddr8_array'] as List<dynamic>)
              .map((e) => e.toString())
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    String? colCidr,
    List<String>? colCidrArray,
    String? colInet,
    List<String>? colInetArray,
    String? colMacaddr,
    List<String>? colMacaddrArray,
    String? colMacaddr8,
    List<String>? colMacaddr8Array,
  }) {
    return {
      if (id != null) 'id': id,
      if (colCidr != null) 'col_cidr': colCidr,
      if (colCidrArray != null) 'col_cidr_array': colCidrArray,
      if (colInet != null) 'col_inet': colInet,
      if (colInetArray != null) 'col_inet_array': colInetArray,
      if (colMacaddr != null) 'col_macaddr': colMacaddr,
      if (colMacaddrArray != null) 'col_macaddr_array': colMacaddrArray,
      if (colMacaddr8 != null) 'col_macaddr8': colMacaddr8,
      if (colMacaddr8Array != null) 'col_macaddr8_array': colMacaddr8Array,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colCidr: colCidr,
      colCidrArray: colCidrArray,
      colInet: colInet,
      colInetArray: colInetArray,
      colMacaddr: colMacaddr,
      colMacaddrArray: colMacaddrArray,
      colMacaddr8: colMacaddr8,
      colMacaddr8Array: colMacaddr8Array,
    );
  }

  static const _unset = Object();
  NetworkTypes copyWith({
    Object? id = _unset,
    Object? colCidr = _unset,
    Object? colCidrArray = _unset,
    Object? colInet = _unset,
    Object? colInetArray = _unset,
    Object? colMacaddr = _unset,
    Object? colMacaddrArray = _unset,
    Object? colMacaddr8 = _unset,
    Object? colMacaddr8Array = _unset,
  }) {
    return NetworkTypes(
      id: id == _unset ? this.id : id as String,
      colCidr: colCidr == _unset ? this.colCidr : colCidr as String?,
      colCidrArray: colCidrArray == _unset
          ? this.colCidrArray
          : colCidrArray as List<String>?,
      colInet: colInet == _unset ? this.colInet : colInet as String?,
      colInetArray: colInetArray == _unset
          ? this.colInetArray
          : colInetArray as List<String>?,
      colMacaddr:
          colMacaddr == _unset ? this.colMacaddr : colMacaddr as String?,
      colMacaddrArray: colMacaddrArray == _unset
          ? this.colMacaddrArray
          : colMacaddrArray as List<String>?,
      colMacaddr8:
          colMacaddr8 == _unset ? this.colMacaddr8 : colMacaddr8 as String?,
      colMacaddr8Array: colMacaddr8Array == _unset
          ? this.colMacaddr8Array
          : colMacaddr8Array as List<String>?,
    );
  }
}
