// ignore_for_file: non_constant_identifier_names, constant_identifier_names, camel_case_types, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class NumericTypes implements SupadartClass<NumericTypes> {
  final String id;
  final BigInt? colBigint;
  final List<BigInt>? colBigintArray;
  final int? colInteger;
  final List<int>? colIntegerArray;
  final int? colSmallint;
  final List<int>? colSmallintArray;
  final double? colDouble;
  final List<double>? colDoubleArray;
  final double? colReal;
  final List<double>? colRealArray;
  final num? colNumeric;
  final List<num>? colNumericArray;

  const NumericTypes({
    required this.id,
    this.colBigint,
    this.colBigintArray,
    this.colInteger,
    this.colIntegerArray,
    this.colSmallint,
    this.colSmallintArray,
    this.colDouble,
    this.colDoubleArray,
    this.colReal,
    this.colRealArray,
    this.colNumeric,
    this.colNumericArray,
  });

  static String get schema_name => 'public';
  static String get table_name => 'numeric_types';
  static String get c_id => 'id';
  static String get c_colBigint => 'col_bigint';
  static String get c_colBigintArray => 'col_bigint_array';
  static String get c_colInteger => 'col_integer';
  static String get c_colIntegerArray => 'col_integer_array';
  static String get c_colSmallint => 'col_smallint';
  static String get c_colSmallintArray => 'col_smallint_array';
  static String get c_colDouble => 'col_double';
  static String get c_colDoubleArray => 'col_double_array';
  static String get c_colReal => 'col_real';
  static String get c_colRealArray => 'col_real_array';
  static String get c_colNumeric => 'col_numeric';
  static String get c_colNumericArray => 'col_numeric_array';

  static List<NumericTypes> converter(List<Map<String, dynamic>> data) {
    return data.map(NumericTypes.fromJson).toList();
  }

  static NumericTypes converterSingle(Map<String, dynamic> data) {
    return NumericTypes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    BigInt? colBigint,
    List<BigInt>? colBigintArray,
    int? colInteger,
    List<int>? colIntegerArray,
    int? colSmallint,
    List<int>? colSmallintArray,
    double? colDouble,
    List<double>? colDoubleArray,
    double? colReal,
    List<double>? colRealArray,
    num? colNumeric,
    List<num>? colNumericArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBigint != null) 'col_bigint': colBigint.toString(),
      if (colBigintArray != null)
        'col_bigint_array': colBigintArray.map((e) => e.toString()).toList(),
      if (colInteger != null) 'col_integer': colInteger,
      if (colIntegerArray != null) 'col_integer_array': colIntegerArray,
      if (colSmallint != null) 'col_smallint': colSmallint,
      if (colSmallintArray != null) 'col_smallint_array': colSmallintArray,
      if (colDouble != null) 'col_double': colDouble.toString(),
      if (colDoubleArray != null)
        'col_double_array': colDoubleArray.map((e) => e.toString()).toList(),
      if (colReal != null) 'col_real': colReal,
      if (colRealArray != null) 'col_real_array': colRealArray,
      if (colNumeric != null) 'col_numeric': colNumeric.toString(),
      if (colNumericArray != null)
        'col_numeric_array': colNumericArray.map((e) => e.toString()).toList(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    BigInt? colBigint,
    List<BigInt>? colBigintArray,
    int? colInteger,
    List<int>? colIntegerArray,
    int? colSmallint,
    List<int>? colSmallintArray,
    double? colDouble,
    List<double>? colDoubleArray,
    double? colReal,
    List<double>? colRealArray,
    num? colNumeric,
    List<num>? colNumericArray,
  }) {
    return _generateMap(
      id: id,
      colBigint: colBigint,
      colBigintArray: colBigintArray,
      colInteger: colInteger,
      colIntegerArray: colIntegerArray,
      colSmallint: colSmallint,
      colSmallintArray: colSmallintArray,
      colDouble: colDouble,
      colDoubleArray: colDoubleArray,
      colReal: colReal,
      colRealArray: colRealArray,
      colNumeric: colNumeric,
      colNumericArray: colNumericArray,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    BigInt? colBigint,
    List<BigInt>? colBigintArray,
    int? colInteger,
    List<int>? colIntegerArray,
    int? colSmallint,
    List<int>? colSmallintArray,
    double? colDouble,
    List<double>? colDoubleArray,
    double? colReal,
    List<double>? colRealArray,
    num? colNumeric,
    List<num>? colNumericArray,
  }) {
    return _generateMap(
      id: id,
      colBigint: colBigint,
      colBigintArray: colBigintArray,
      colInteger: colInteger,
      colIntegerArray: colIntegerArray,
      colSmallint: colSmallint,
      colSmallintArray: colSmallintArray,
      colDouble: colDouble,
      colDoubleArray: colDoubleArray,
      colReal: colReal,
      colRealArray: colRealArray,
      colNumeric: colNumeric,
      colNumericArray: colNumericArray,
    );
  }

  factory NumericTypes.fromJson(Map<String, dynamic> jsonn) {
    return NumericTypes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      colBigint: jsonn['col_bigint'] != null
          ? BigInt.parse(jsonn['col_bigint'].toString())
          : null,
      colBigintArray: jsonn['col_bigint_array'] != null
          ? (jsonn['col_bigint_array'] as List<dynamic>)
              .map((v) => BigInt.parse(v.toString()))
              .toList()
          : null,
      colInteger: jsonn['col_integer'] != null
          ? int.parse(jsonn['col_integer'].toString())
          : null,
      colIntegerArray: jsonn['col_integer_array'] != null
          ? (jsonn['col_integer_array'] as List<dynamic>)
              .map((v) => int.parse(v.toString()))
              .toList()
          : null,
      colSmallint: jsonn['col_smallint'] != null
          ? int.parse(jsonn['col_smallint'].toString())
          : null,
      colSmallintArray: jsonn['col_smallint_array'] != null
          ? (jsonn['col_smallint_array'] as List<dynamic>)
              .map((v) => int.parse(v.toString()))
              .toList()
          : null,
      colDouble: jsonn['col_double'] != null
          ? double.parse(jsonn['col_double'].toString())
          : null,
      colDoubleArray: jsonn['col_double_array'] != null
          ? (jsonn['col_double_array'] as List<dynamic>)
              .map((v) => double.parse(v.toString()))
              .toList()
          : null,
      colReal: jsonn['col_real'] != null
          ? double.parse(jsonn['col_real'].toString())
          : null,
      colRealArray: jsonn['col_real_array'] != null
          ? (jsonn['col_real_array'] as List<dynamic>)
              .map((v) => double.parse(v.toString()))
              .toList()
          : null,
      colNumeric: jsonn['col_numeric'] != null
          ? num.parse(jsonn['col_numeric'].toString())
          : null,
      colNumericArray: jsonn['col_numeric_array'] != null
          ? (jsonn['col_numeric_array'] as List<dynamic>)
              .map((v) => num.parse(v.toString()))
              .toList()
          : null,
    );
  }

  static Object New({
    String? id,
    BigInt? colBigint,
    List<BigInt>? colBigintArray,
    int? colInteger,
    List<int>? colIntegerArray,
    int? colSmallint,
    List<int>? colSmallintArray,
    double? colDouble,
    List<double>? colDoubleArray,
    double? colReal,
    List<double>? colRealArray,
    num? colNumeric,
    List<num>? colNumericArray,
  }) {
    return {
      if (id != null) 'id': id,
      if (colBigint != null) 'col_bigint': colBigint,
      if (colBigintArray != null) 'col_bigint_array': colBigintArray,
      if (colInteger != null) 'col_integer': colInteger,
      if (colIntegerArray != null) 'col_integer_array': colIntegerArray,
      if (colSmallint != null) 'col_smallint': colSmallint,
      if (colSmallintArray != null) 'col_smallint_array': colSmallintArray,
      if (colDouble != null) 'col_double': colDouble,
      if (colDoubleArray != null) 'col_double_array': colDoubleArray,
      if (colReal != null) 'col_real': colReal,
      if (colRealArray != null) 'col_real_array': colRealArray,
      if (colNumeric != null) 'col_numeric': colNumeric,
      if (colNumericArray != null) 'col_numeric_array': colNumericArray,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      colBigint: colBigint,
      colBigintArray: colBigintArray,
      colInteger: colInteger,
      colIntegerArray: colIntegerArray,
      colSmallint: colSmallint,
      colSmallintArray: colSmallintArray,
      colDouble: colDouble,
      colDoubleArray: colDoubleArray,
      colReal: colReal,
      colRealArray: colRealArray,
      colNumeric: colNumeric,
      colNumericArray: colNumericArray,
    );
  }

  static const _unset = Object();
  NumericTypes copyWith({
    Object? id = _unset,
    Object? colBigint = _unset,
    Object? colBigintArray = _unset,
    Object? colInteger = _unset,
    Object? colIntegerArray = _unset,
    Object? colSmallint = _unset,
    Object? colSmallintArray = _unset,
    Object? colDouble = _unset,
    Object? colDoubleArray = _unset,
    Object? colReal = _unset,
    Object? colRealArray = _unset,
    Object? colNumeric = _unset,
    Object? colNumericArray = _unset,
  }) {
    return NumericTypes(
      id: id == _unset ? this.id : id as String,
      colBigint: colBigint == _unset ? this.colBigint : colBigint as BigInt?,
      colBigintArray: colBigintArray == _unset
          ? this.colBigintArray
          : colBigintArray as List<BigInt>?,
      colInteger: colInteger == _unset ? this.colInteger : colInteger as int?,
      colIntegerArray: colIntegerArray == _unset
          ? this.colIntegerArray
          : colIntegerArray as List<int>?,
      colSmallint:
          colSmallint == _unset ? this.colSmallint : colSmallint as int?,
      colSmallintArray: colSmallintArray == _unset
          ? this.colSmallintArray
          : colSmallintArray as List<int>?,
      colDouble: colDouble == _unset ? this.colDouble : colDouble as double?,
      colDoubleArray: colDoubleArray == _unset
          ? this.colDoubleArray
          : colDoubleArray as List<double>?,
      colReal: colReal == _unset ? this.colReal : colReal as double?,
      colRealArray: colRealArray == _unset
          ? this.colRealArray
          : colRealArray as List<double>?,
      colNumeric: colNumeric == _unset ? this.colNumeric : colNumeric as num?,
      colNumericArray: colNumericArray == _unset
          ? this.colNumericArray
          : colNumericArray as List<num>?,
    );
  }
}
