-- A second exposed schema (see [api] schemas in config.toml) for generating
-- models from more than one schema. Its names deliberately overlap public's:
-- a `profiles` table and a `mood` enum with different labels.
DROP SCHEMA IF EXISTS inventory CASCADE;
CREATE SCHEMA inventory;

GRANT USAGE ON SCHEMA inventory TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

CREATE TYPE inventory.item_status AS ENUM ('in_stock', 'backordered', 'discontinued');
CREATE TYPE inventory.mood AS ENUM ('calm', 'busy');

CREATE TABLE inventory.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status inventory.item_status NOT NULL DEFAULT 'in_stock',
    status_history inventory.item_status[] NULL,
    -- An enum from another schema.
    owner_mood public.mood NULL,
    warehouse_mood inventory.mood NULL,
    attributes JSONB NULL
);

CREATE TABLE inventory.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    display_name TEXT NOT NULL
);
